// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ehenxlhyofsyqcnsxjhq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVoZW54bGh5b2ZzeXFjbnN4amhxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQzNzgwNjksImV4cCI6MjA2OTk1NDA2OX0.LmFyaieEk4xZqiYmgsQnR1oaL5sts9f7ezbsBvLEoWM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});